# Generated by Django 3.2.5 on 2021-07-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('descripcion', models.CharField(default='', max_length=300)),
                ('precio', models.IntegerField(default=0)),
                ('ruta', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
